FROM node:20-alpine AS builder

WORKDIR /app
COPY web/package*.json ./
RUN npm install
ARG ENV=local
COPY web/ .
RUN cp env/.env.${ENV} .env
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY web/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80