services:
  api:
    image: ${APPNAME}-${ENV}-api-img
    container_name: ${APPNAME}-${ENV}-api-svc
    build:
      context: .
      dockerfile: dockerfile.api
      args:
        APPNAME: ${APPNAME}
        PORT: ${API_PORT}
    env_file:
      - api/env/.env.${ENV}   
    networks:
      - ${APPNAME}-network  
    ports:
      - "${API_PORT}:${API_PORT}"
    secrets:
      - db_password   
      - via_auth
      - oauth_client_secret
      - jwt_private_key 
      - jwt_public_key
      - ds_password
    depends_on:
      - db  
      - ds

  web:
    build:
      context: .
      dockerfile: dockerfile.web
      args:
        ENV: ${ENV}
        PORT: ${WEB_PORT}
    environment:
      PORT: ${WEB_PORT} 
    image: ${APPNAME}-${ENV}-web-img
    container_name: ${APPNAME}-${ENV}-web-svc
    ports:
      - "${WEB_PORT}:80"
    networks:
      - via-network  
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: ${APPNAME}-${ENV}-db
    env_file:
      - db/env/.env.${ENV}  
    volumes:
      - ./db_data.${ENV}:/var/lib/postgresql/data 
      - ./db/conf/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./db/script/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: >
      -c hba_file=/etc/postgresql/pg_hba.conf  
    networks:
      - ${APPNAME}-network
    secrets:
      - db_password
    ports:
      - "${DB_PORT}:5432"

  ds:
    image: redis:7
    container_name: ${APPNAME}-${ENV}-redis
    env_file:
      - ds/env/.env.${ENV}   
    networks:
      - ${APPNAME}-network
    ports:
      - "${DS_PORT}:6379"
    volumes:
      - ./ds_data.${ENV}:/data
    secrets:
      - ds_password
    command: >
      redis-server --requirepass "$(cat /run/secrets/ds_password)"

networks:
  via-network:
    name: ${APPNAME}-${ENV}-net
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.${ENV}
  via_auth:
    file: ./secrets/via_auth.${ENV}
  oauth_client_secret:
    file: ./secrets/oauth_client_secret.${ENV}
  jwt_private_key:
    file: ./secrets/jwt_private_key.${ENV}
  jwt_public_key:
    file: ./secrets/jwt_public_key.${ENV}
  ds_password:
    file: ./secrets/ds_password.${ENV}  
