// Code generated by ent, DO NOT EDIT.

package operator

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the operator type in the database.
	Label = "operator"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccount holds the string denoting the account field in the database.
	FieldAccount = "account"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeGuideProcesses holds the string denoting the guide_processes edge name in mutations.
	EdgeGuideProcesses = "guide_processes"
	// EdgeGuideProcessHistories holds the string denoting the guide_process_histories edge name in mutations.
	EdgeGuideProcessHistories = "guide_process_histories"
	// Table holds the table name of the operator in the database.
	Table = "operators"
	// GuideProcessesTable is the table that holds the guide_processes relation/edge.
	GuideProcessesTable = "guide_processes"
	// GuideProcessesInverseTable is the table name for the GuideProcess entity.
	// It exists in this package in order to avoid circular dependency with the "guideprocess" package.
	GuideProcessesInverseTable = "guide_processes"
	// GuideProcessesColumn is the table column denoting the guide_processes relation/edge.
	GuideProcessesColumn = "operator_guide_processes"
	// GuideProcessHistoriesTable is the table that holds the guide_process_histories relation/edge.
	GuideProcessHistoriesTable = "guide_process_histories"
	// GuideProcessHistoriesInverseTable is the table name for the GuideProcessHistory entity.
	// It exists in this package in order to avoid circular dependency with the "guideprocesshistory" package.
	GuideProcessHistoriesInverseTable = "guide_process_histories"
	// GuideProcessHistoriesColumn is the table column denoting the guide_process_histories relation/edge.
	GuideProcessHistoriesColumn = "operator_guide_process_histories"
)

// Columns holds all SQL columns for operator fields.
var Columns = []string{
	FieldID,
	FieldAccount,
	FieldEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AccountValidator is a validator for the "account" field. It is called by the builders before save.
	AccountValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Operator queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccount orders the results by the account field.
func ByAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccount, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGuideProcessesCount orders the results by guide_processes count.
func ByGuideProcessesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGuideProcessesStep(), opts...)
	}
}

// ByGuideProcesses orders the results by guide_processes terms.
func ByGuideProcesses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGuideProcessesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGuideProcessHistoriesCount orders the results by guide_process_histories count.
func ByGuideProcessHistoriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGuideProcessHistoriesStep(), opts...)
	}
}

// ByGuideProcessHistories orders the results by guide_process_histories terms.
func ByGuideProcessHistories(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGuideProcessHistoriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGuideProcessesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GuideProcessesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GuideProcessesTable, GuideProcessesColumn),
	)
}
func newGuideProcessHistoriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GuideProcessHistoriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GuideProcessHistoriesTable, GuideProcessHistoriesColumn),
	)
}
