// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"via/internal/ent/guidehistory"
	"via/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GuideHistoryDelete is the builder for deleting a GuideHistory entity.
type GuideHistoryDelete struct {
	config
	hooks    []Hook
	mutation *GuideHistoryMutation
}

// Where appends a list predicates to the GuideHistoryDelete builder.
func (ghd *GuideHistoryDelete) Where(ps ...predicate.GuideHistory) *GuideHistoryDelete {
	ghd.mutation.Where(ps...)
	return ghd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ghd *GuideHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ghd.sqlExec, ghd.mutation, ghd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ghd *GuideHistoryDelete) ExecX(ctx context.Context) int {
	n, err := ghd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ghd *GuideHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(guidehistory.Table, sqlgraph.NewFieldSpec(guidehistory.FieldID, field.TypeInt))
	if ps := ghd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ghd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ghd.mutation.done = true
	return affected, err
}

// GuideHistoryDeleteOne is the builder for deleting a single GuideHistory entity.
type GuideHistoryDeleteOne struct {
	ghd *GuideHistoryDelete
}

// Where appends a list predicates to the GuideHistoryDelete builder.
func (ghdo *GuideHistoryDeleteOne) Where(ps ...predicate.GuideHistory) *GuideHistoryDeleteOne {
	ghdo.ghd.mutation.Where(ps...)
	return ghdo
}

// Exec executes the deletion query.
func (ghdo *GuideHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := ghdo.ghd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{guidehistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ghdo *GuideHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := ghdo.Exec(ctx); err != nil {
		panic(err)
	}
}
