// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"via/internal/ent/guide"
	"via/internal/ent/guidehistory"
	"via/internal/ent/operator"
	"via/internal/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GuideHistoryQuery is the builder for querying GuideHistory entities.
type GuideHistoryQuery struct {
	config
	ctx          *QueryContext
	order        []guidehistory.OrderOption
	inters       []Interceptor
	predicates   []predicate.GuideHistory
	withGuide    *GuideQuery
	withOperator *OperatorQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GuideHistoryQuery builder.
func (ghq *GuideHistoryQuery) Where(ps ...predicate.GuideHistory) *GuideHistoryQuery {
	ghq.predicates = append(ghq.predicates, ps...)
	return ghq
}

// Limit the number of records to be returned by this query.
func (ghq *GuideHistoryQuery) Limit(limit int) *GuideHistoryQuery {
	ghq.ctx.Limit = &limit
	return ghq
}

// Offset to start from.
func (ghq *GuideHistoryQuery) Offset(offset int) *GuideHistoryQuery {
	ghq.ctx.Offset = &offset
	return ghq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ghq *GuideHistoryQuery) Unique(unique bool) *GuideHistoryQuery {
	ghq.ctx.Unique = &unique
	return ghq
}

// Order specifies how the records should be ordered.
func (ghq *GuideHistoryQuery) Order(o ...guidehistory.OrderOption) *GuideHistoryQuery {
	ghq.order = append(ghq.order, o...)
	return ghq
}

// QueryGuide chains the current query on the "guide" edge.
func (ghq *GuideHistoryQuery) QueryGuide() *GuideQuery {
	query := (&GuideClient{config: ghq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ghq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ghq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(guidehistory.Table, guidehistory.FieldID, selector),
			sqlgraph.To(guide.Table, guide.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, guidehistory.GuideTable, guidehistory.GuideColumn),
		)
		fromU = sqlgraph.SetNeighbors(ghq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOperator chains the current query on the "operator" edge.
func (ghq *GuideHistoryQuery) QueryOperator() *OperatorQuery {
	query := (&OperatorClient{config: ghq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ghq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ghq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(guidehistory.Table, guidehistory.FieldID, selector),
			sqlgraph.To(operator.Table, operator.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, guidehistory.OperatorTable, guidehistory.OperatorColumn),
		)
		fromU = sqlgraph.SetNeighbors(ghq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GuideHistory entity from the query.
// Returns a *NotFoundError when no GuideHistory was found.
func (ghq *GuideHistoryQuery) First(ctx context.Context) (*GuideHistory, error) {
	nodes, err := ghq.Limit(1).All(setContextOp(ctx, ghq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{guidehistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ghq *GuideHistoryQuery) FirstX(ctx context.Context) *GuideHistory {
	node, err := ghq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GuideHistory ID from the query.
// Returns a *NotFoundError when no GuideHistory ID was found.
func (ghq *GuideHistoryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ghq.Limit(1).IDs(setContextOp(ctx, ghq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{guidehistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ghq *GuideHistoryQuery) FirstIDX(ctx context.Context) int {
	id, err := ghq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GuideHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GuideHistory entity is found.
// Returns a *NotFoundError when no GuideHistory entities are found.
func (ghq *GuideHistoryQuery) Only(ctx context.Context) (*GuideHistory, error) {
	nodes, err := ghq.Limit(2).All(setContextOp(ctx, ghq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{guidehistory.Label}
	default:
		return nil, &NotSingularError{guidehistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ghq *GuideHistoryQuery) OnlyX(ctx context.Context) *GuideHistory {
	node, err := ghq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GuideHistory ID in the query.
// Returns a *NotSingularError when more than one GuideHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (ghq *GuideHistoryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ghq.Limit(2).IDs(setContextOp(ctx, ghq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{guidehistory.Label}
	default:
		err = &NotSingularError{guidehistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ghq *GuideHistoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := ghq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GuideHistories.
func (ghq *GuideHistoryQuery) All(ctx context.Context) ([]*GuideHistory, error) {
	ctx = setContextOp(ctx, ghq.ctx, ent.OpQueryAll)
	if err := ghq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GuideHistory, *GuideHistoryQuery]()
	return withInterceptors[[]*GuideHistory](ctx, ghq, qr, ghq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ghq *GuideHistoryQuery) AllX(ctx context.Context) []*GuideHistory {
	nodes, err := ghq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GuideHistory IDs.
func (ghq *GuideHistoryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ghq.ctx.Unique == nil && ghq.path != nil {
		ghq.Unique(true)
	}
	ctx = setContextOp(ctx, ghq.ctx, ent.OpQueryIDs)
	if err = ghq.Select(guidehistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ghq *GuideHistoryQuery) IDsX(ctx context.Context) []int {
	ids, err := ghq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ghq *GuideHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ghq.ctx, ent.OpQueryCount)
	if err := ghq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ghq, querierCount[*GuideHistoryQuery](), ghq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ghq *GuideHistoryQuery) CountX(ctx context.Context) int {
	count, err := ghq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ghq *GuideHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ghq.ctx, ent.OpQueryExist)
	switch _, err := ghq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ghq *GuideHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := ghq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GuideHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ghq *GuideHistoryQuery) Clone() *GuideHistoryQuery {
	if ghq == nil {
		return nil
	}
	return &GuideHistoryQuery{
		config:       ghq.config,
		ctx:          ghq.ctx.Clone(),
		order:        append([]guidehistory.OrderOption{}, ghq.order...),
		inters:       append([]Interceptor{}, ghq.inters...),
		predicates:   append([]predicate.GuideHistory{}, ghq.predicates...),
		withGuide:    ghq.withGuide.Clone(),
		withOperator: ghq.withOperator.Clone(),
		// clone intermediate query.
		sql:  ghq.sql.Clone(),
		path: ghq.path,
	}
}

// WithGuide tells the query-builder to eager-load the nodes that are connected to
// the "guide" edge. The optional arguments are used to configure the query builder of the edge.
func (ghq *GuideHistoryQuery) WithGuide(opts ...func(*GuideQuery)) *GuideHistoryQuery {
	query := (&GuideClient{config: ghq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ghq.withGuide = query
	return ghq
}

// WithOperator tells the query-builder to eager-load the nodes that are connected to
// the "operator" edge. The optional arguments are used to configure the query builder of the edge.
func (ghq *GuideHistoryQuery) WithOperator(opts ...func(*OperatorQuery)) *GuideHistoryQuery {
	query := (&OperatorClient{config: ghq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ghq.withOperator = query
	return ghq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status string `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GuideHistory.Query().
//		GroupBy(guidehistory.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ghq *GuideHistoryQuery) GroupBy(field string, fields ...string) *GuideHistoryGroupBy {
	ghq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GuideHistoryGroupBy{build: ghq}
	grbuild.flds = &ghq.ctx.Fields
	grbuild.label = guidehistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status string `json:"status,omitempty"`
//	}
//
//	client.GuideHistory.Query().
//		Select(guidehistory.FieldStatus).
//		Scan(ctx, &v)
func (ghq *GuideHistoryQuery) Select(fields ...string) *GuideHistorySelect {
	ghq.ctx.Fields = append(ghq.ctx.Fields, fields...)
	sbuild := &GuideHistorySelect{GuideHistoryQuery: ghq}
	sbuild.label = guidehistory.Label
	sbuild.flds, sbuild.scan = &ghq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GuideHistorySelect configured with the given aggregations.
func (ghq *GuideHistoryQuery) Aggregate(fns ...AggregateFunc) *GuideHistorySelect {
	return ghq.Select().Aggregate(fns...)
}

func (ghq *GuideHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ghq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ghq); err != nil {
				return err
			}
		}
	}
	for _, f := range ghq.ctx.Fields {
		if !guidehistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ghq.path != nil {
		prev, err := ghq.path(ctx)
		if err != nil {
			return err
		}
		ghq.sql = prev
	}
	return nil
}

func (ghq *GuideHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GuideHistory, error) {
	var (
		nodes       = []*GuideHistory{}
		withFKs     = ghq.withFKs
		_spec       = ghq.querySpec()
		loadedTypes = [2]bool{
			ghq.withGuide != nil,
			ghq.withOperator != nil,
		}
	)
	if ghq.withGuide != nil || ghq.withOperator != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, guidehistory.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GuideHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GuideHistory{config: ghq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ghq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ghq.withGuide; query != nil {
		if err := ghq.loadGuide(ctx, query, nodes, nil,
			func(n *GuideHistory, e *Guide) { n.Edges.Guide = e }); err != nil {
			return nil, err
		}
	}
	if query := ghq.withOperator; query != nil {
		if err := ghq.loadOperator(ctx, query, nodes, nil,
			func(n *GuideHistory, e *Operator) { n.Edges.Operator = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ghq *GuideHistoryQuery) loadGuide(ctx context.Context, query *GuideQuery, nodes []*GuideHistory, init func(*GuideHistory), assign func(*GuideHistory, *Guide)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*GuideHistory)
	for i := range nodes {
		if nodes[i].guide_history == nil {
			continue
		}
		fk := *nodes[i].guide_history
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(guide.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "guide_history" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ghq *GuideHistoryQuery) loadOperator(ctx context.Context, query *OperatorQuery, nodes []*GuideHistory, init func(*GuideHistory), assign func(*GuideHistory, *Operator)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*GuideHistory)
	for i := range nodes {
		if nodes[i].operator_guide_history == nil {
			continue
		}
		fk := *nodes[i].operator_guide_history
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(operator.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "operator_guide_history" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ghq *GuideHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ghq.querySpec()
	_spec.Node.Columns = ghq.ctx.Fields
	if len(ghq.ctx.Fields) > 0 {
		_spec.Unique = ghq.ctx.Unique != nil && *ghq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ghq.driver, _spec)
}

func (ghq *GuideHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(guidehistory.Table, guidehistory.Columns, sqlgraph.NewFieldSpec(guidehistory.FieldID, field.TypeInt))
	_spec.From = ghq.sql
	if unique := ghq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ghq.path != nil {
		_spec.Unique = true
	}
	if fields := ghq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, guidehistory.FieldID)
		for i := range fields {
			if fields[i] != guidehistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ghq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ghq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ghq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ghq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ghq *GuideHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ghq.driver.Dialect())
	t1 := builder.Table(guidehistory.Table)
	columns := ghq.ctx.Fields
	if len(columns) == 0 {
		columns = guidehistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ghq.sql != nil {
		selector = ghq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ghq.ctx.Unique != nil && *ghq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ghq.predicates {
		p(selector)
	}
	for _, p := range ghq.order {
		p(selector)
	}
	if offset := ghq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ghq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GuideHistoryGroupBy is the group-by builder for GuideHistory entities.
type GuideHistoryGroupBy struct {
	selector
	build *GuideHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ghgb *GuideHistoryGroupBy) Aggregate(fns ...AggregateFunc) *GuideHistoryGroupBy {
	ghgb.fns = append(ghgb.fns, fns...)
	return ghgb
}

// Scan applies the selector query and scans the result into the given value.
func (ghgb *GuideHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ghgb.build.ctx, ent.OpQueryGroupBy)
	if err := ghgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GuideHistoryQuery, *GuideHistoryGroupBy](ctx, ghgb.build, ghgb, ghgb.build.inters, v)
}

func (ghgb *GuideHistoryGroupBy) sqlScan(ctx context.Context, root *GuideHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ghgb.fns))
	for _, fn := range ghgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ghgb.flds)+len(ghgb.fns))
		for _, f := range *ghgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ghgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ghgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GuideHistorySelect is the builder for selecting fields of GuideHistory entities.
type GuideHistorySelect struct {
	*GuideHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ghs *GuideHistorySelect) Aggregate(fns ...AggregateFunc) *GuideHistorySelect {
	ghs.fns = append(ghs.fns, fns...)
	return ghs
}

// Scan applies the selector query and scans the result into the given value.
func (ghs *GuideHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ghs.ctx, ent.OpQuerySelect)
	if err := ghs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GuideHistoryQuery, *GuideHistorySelect](ctx, ghs.GuideHistoryQuery, ghs, ghs.inters, v)
}

func (ghs *GuideHistorySelect) sqlScan(ctx context.Context, root *GuideHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ghs.fns))
	for _, fn := range ghs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ghs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ghs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
