// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"via/internal/ent/guide"
	"via/internal/ent/guidehistory"
	"via/internal/ent/operator"
	"via/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	guideFields := schema.Guide{}.Fields()
	_ = guideFields
	// guideDescCode is the schema descriptor for code field.
	guideDescCode := guideFields[0].Descriptor()
	// guide.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	guide.CodeValidator = func() func(string) error {
		validators := guideDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// guideDescRecipient is the schema descriptor for recipient field.
	guideDescRecipient := guideFields[1].Descriptor()
	// guide.RecipientValidator is a validator for the "recipient" field. It is called by the builders before save.
	guide.RecipientValidator = guideDescRecipient.Validators[0].(func(string) error)
	// guideDescStatus is the schema descriptor for status field.
	guideDescStatus := guideFields[2].Descriptor()
	// guide.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	guide.StatusValidator = guideDescStatus.Validators[0].(func(string) error)
	// guideDescCreatedAt is the schema descriptor for created_at field.
	guideDescCreatedAt := guideFields[3].Descriptor()
	// guide.DefaultCreatedAt holds the default value on creation for the created_at field.
	guide.DefaultCreatedAt = guideDescCreatedAt.Default.(func() time.Time)
	// guideDescUpdatedAt is the schema descriptor for updated_at field.
	guideDescUpdatedAt := guideFields[4].Descriptor()
	// guide.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	guide.DefaultUpdatedAt = guideDescUpdatedAt.Default.(func() time.Time)
	// guide.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	guide.UpdateDefaultUpdatedAt = guideDescUpdatedAt.UpdateDefault.(func() time.Time)
	guidehistoryFields := schema.GuideHistory{}.Fields()
	_ = guidehistoryFields
	// guidehistoryDescStatus is the schema descriptor for status field.
	guidehistoryDescStatus := guidehistoryFields[0].Descriptor()
	// guidehistory.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	guidehistory.StatusValidator = guidehistoryDescStatus.Validators[0].(func(string) error)
	// guidehistoryDescCreatedAt is the schema descriptor for created_at field.
	guidehistoryDescCreatedAt := guidehistoryFields[1].Descriptor()
	// guidehistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	guidehistory.DefaultCreatedAt = guidehistoryDescCreatedAt.Default.(func() time.Time)
	operatorFields := schema.Operator{}.Fields()
	_ = operatorFields
	// operatorDescAccount is the schema descriptor for account field.
	operatorDescAccount := operatorFields[0].Descriptor()
	// operator.AccountValidator is a validator for the "account" field. It is called by the builders before save.
	operator.AccountValidator = operatorDescAccount.Validators[0].(func(string) error)
	// operatorDescCreatedAt is the schema descriptor for created_at field.
	operatorDescCreatedAt := operatorFields[2].Descriptor()
	// operator.DefaultCreatedAt holds the default value on creation for the created_at field.
	operator.DefaultCreatedAt = operatorDescCreatedAt.Default.(func() time.Time)
	// operatorDescUpdatedAt is the schema descriptor for updated_at field.
	operatorDescUpdatedAt := operatorFields[3].Descriptor()
	// operator.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	operator.DefaultUpdatedAt = operatorDescUpdatedAt.Default.(func() time.Time)
	// operator.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	operator.UpdateDefaultUpdatedAt = operatorDescUpdatedAt.UpdateDefault.(func() time.Time)
}
