// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"via/internal/ent/guideprocess"
	"via/internal/ent/guideprocesshistory"
	"via/internal/ent/operator"
	"via/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	guideprocessFields := schema.GuideProcess{}.Fields()
	_ = guideprocessFields
	// guideprocessDescCode is the schema descriptor for code field.
	guideprocessDescCode := guideprocessFields[0].Descriptor()
	// guideprocess.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	guideprocess.CodeValidator = func() func(string) error {
		validators := guideprocessDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// guideprocessDescRecipient is the schema descriptor for recipient field.
	guideprocessDescRecipient := guideprocessFields[1].Descriptor()
	// guideprocess.RecipientValidator is a validator for the "recipient" field. It is called by the builders before save.
	guideprocess.RecipientValidator = guideprocessDescRecipient.Validators[0].(func(string) error)
	// guideprocessDescStatus is the schema descriptor for status field.
	guideprocessDescStatus := guideprocessFields[2].Descriptor()
	// guideprocess.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	guideprocess.StatusValidator = guideprocessDescStatus.Validators[0].(func(string) error)
	// guideprocessDescCreatedAt is the schema descriptor for created_at field.
	guideprocessDescCreatedAt := guideprocessFields[3].Descriptor()
	// guideprocess.DefaultCreatedAt holds the default value on creation for the created_at field.
	guideprocess.DefaultCreatedAt = guideprocessDescCreatedAt.Default.(func() time.Time)
	// guideprocessDescUpdatedAt is the schema descriptor for updated_at field.
	guideprocessDescUpdatedAt := guideprocessFields[4].Descriptor()
	// guideprocess.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	guideprocess.DefaultUpdatedAt = guideprocessDescUpdatedAt.Default.(func() time.Time)
	// guideprocess.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	guideprocess.UpdateDefaultUpdatedAt = guideprocessDescUpdatedAt.UpdateDefault.(func() time.Time)
	guideprocesshistoryFields := schema.GuideProcessHistory{}.Fields()
	_ = guideprocesshistoryFields
	// guideprocesshistoryDescStatus is the schema descriptor for status field.
	guideprocesshistoryDescStatus := guideprocesshistoryFields[0].Descriptor()
	// guideprocesshistory.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	guideprocesshistory.StatusValidator = guideprocesshistoryDescStatus.Validators[0].(func(string) error)
	// guideprocesshistoryDescCreatedAt is the schema descriptor for created_at field.
	guideprocesshistoryDescCreatedAt := guideprocesshistoryFields[1].Descriptor()
	// guideprocesshistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	guideprocesshistory.DefaultCreatedAt = guideprocesshistoryDescCreatedAt.Default.(func() time.Time)
	operatorFields := schema.Operator{}.Fields()
	_ = operatorFields
	// operatorDescAccount is the schema descriptor for account field.
	operatorDescAccount := operatorFields[0].Descriptor()
	// operator.AccountValidator is a validator for the "account" field. It is called by the builders before save.
	operator.AccountValidator = operatorDescAccount.Validators[0].(func(string) error)
	// operatorDescCreatedAt is the schema descriptor for created_at field.
	operatorDescCreatedAt := operatorFields[2].Descriptor()
	// operator.DefaultCreatedAt holds the default value on creation for the created_at field.
	operator.DefaultCreatedAt = operatorDescCreatedAt.Default.(func() time.Time)
	// operatorDescUpdatedAt is the schema descriptor for updated_at field.
	operatorDescUpdatedAt := operatorFields[3].Descriptor()
	// operator.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	operator.DefaultUpdatedAt = operatorDescUpdatedAt.Default.(func() time.Time)
	// operator.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	operator.UpdateDefaultUpdatedAt = operatorDescUpdatedAt.UpdateDefault.(func() time.Time)
}
