// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GuideProcessesColumns holds the columns for the "guide_processes" table.
	GuideProcessesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 12},
		{Name: "recipient", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "status", Type: field.TypeString, Nullable: true, Size: 30},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "operator_guide_processes", Type: field.TypeInt, Nullable: true},
	}
	// GuideProcessesTable holds the schema information for the "guide_processes" table.
	GuideProcessesTable = &schema.Table{
		Name:       "guide_processes",
		Columns:    GuideProcessesColumns,
		PrimaryKey: []*schema.Column{GuideProcessesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "guide_processes_operators_guide_processes",
				Columns:    []*schema.Column{GuideProcessesColumns[6]},
				RefColumns: []*schema.Column{OperatorsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// GuideProcessHistoriesColumns holds the columns for the "guide_process_histories" table.
	GuideProcessHistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeString, Nullable: true, Size: 30},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "guide_process_history", Type: field.TypeInt},
		{Name: "operator_guide_process_histories", Type: field.TypeInt, Nullable: true},
	}
	// GuideProcessHistoriesTable holds the schema information for the "guide_process_histories" table.
	GuideProcessHistoriesTable = &schema.Table{
		Name:       "guide_process_histories",
		Columns:    GuideProcessHistoriesColumns,
		PrimaryKey: []*schema.Column{GuideProcessHistoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "guide_process_histories_guide_processes_history",
				Columns:    []*schema.Column{GuideProcessHistoriesColumns[3]},
				RefColumns: []*schema.Column{GuideProcessesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "guide_process_histories_operators_guide_process_histories",
				Columns:    []*schema.Column{GuideProcessHistoriesColumns[4]},
				RefColumns: []*schema.Column{OperatorsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// OperatorsColumns holds the columns for the "operators" table.
	OperatorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account", Type: field.TypeString, Unique: true},
		{Name: "enabled", Type: field.TypeBool},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OperatorsTable holds the schema information for the "operators" table.
	OperatorsTable = &schema.Table{
		Name:       "operators",
		Columns:    OperatorsColumns,
		PrimaryKey: []*schema.Column{OperatorsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GuideProcessesTable,
		GuideProcessHistoriesTable,
		OperatorsTable,
	}
)

func init() {
	GuideProcessesTable.ForeignKeys[0].RefTable = OperatorsTable
	GuideProcessHistoriesTable.ForeignKeys[0].RefTable = GuideProcessesTable
	GuideProcessHistoriesTable.ForeignKeys[1].RefTable = OperatorsTable
}
